### ISSUE TITLE
#hostname broken sinсe 1.1.4

### ISSUE THREAD

**Issue by onoga** [juxt/aero#105]
function env was renamed to get-env, but forgot to rename call `(env "HOSTNAME")`

https://github.com/juxt/aero/pull/104

**Comment by wardle** [comment]
While waiting for the PR containing the fix for this to be merged, it is possible to recreate this functionality using your own tagged literal e.g. `#host` instead of `#hostname`:

e.g. Add this to a namespace before reading in configuration file:

```Clojure
(defmethod aero.alpha.core/eval-tagged-literal 'host
  [tl {:keys [hostname] :as opts} env ks]
  (aero.alpha.core/expand-case (or hostname (System/getenv "HOSTNAME"))
               tl opts env ks))
```

**Comment by kauppilainen** [comment]
#104 merged
