### ISSUE TITLE
Support for regexps

### ISSUE THREAD

**Issue by abcdw** [juxt/aero#108]
Is there a way to properly read regexp literals by default?

I would like to read edn file with content like this using aero:
`{:regexp #"regexp-here"}`

Right now it complains:
`"No dispatch macro for: \""`

**Comment by SevereOverfl0w** [comment]
EDN doesn't support regex.  One idea might be to use https://github.com/borkdude/edamame/ which would also give the opportunity for better error messages.

**Comment by abcdw** [comment]
@SevereOverfl0w edamame looks great, thank you very much for the mentioning it. I'm curious how hard to implement `#ref` with edamame.
