### ISSUE TITLE
How to rely in one reader on something coming from another reader?

### ISSUE THREAD

**Issue by licht1stein** [juxt/aero#109]
Hi and thanks for the lib!

Is it possible for me to have the following use case:

```clojure
{:token #my-reader-1 SECRET_TOKEN
 :value-that-uses-token #my-reader-2 "secret-value"}
```

```clojure
(defmethod reader 'my-reader-2
  [{:keys [token]} tag value]
  (get-value-using-token token value))
```

The problem is, that all reader tags seem to be resolved at the same time, so I don't see a way to rely in one reader on something coming from another reader. Is there a way to do that?

**Comment by licht1stein** [comment]
The only way I found it to work is like this, but it seems to be a bit too much:

```clojure
{:secrets #include #join [#env HOME "/.secrets/example.edn"]

 :onepass {:token #profile {:dev #ref [:secrets :onepass :token]}
           :base-url "https://example.com/v1"}

 :test-secret #onepass [#ref [:onepass] "onepass-record-details"]}
```

This way I get the onepass credentials as the first element in the value vector and can use it to get the actual secret.

**Comment by SevereOverfl0w** [comment]
I'm confused about what you're expecting to happen in the original example?

**Comment by licht1stein** [comment]
I want to retrieve an api token for 1Password from one reader, and then use it to resolve entries with #onepass reader. So in the 'onepass resolver I need access to the token.

**Comment by licht1stein** [comment]
I have incorrect destructuring there, because I didn't look into the map that comes in. Thought it was the config itself.

**Comment by SevereOverfl0w** [comment]
Why do you want to use a reader to fetch the 1Password api token?

Could you use a vector? `#onepass [#ref [:1pw-api-token] "name-of-secret"]`?

**Comment by licht1stein** [comment]
Yes, it works like this, but it's kinda ugly and long... I want to be able to make a second-stage reader. First stage — get the token, second stage — use token.

**Comment by SevereOverfl0w** [comment]
That would involve state being stored, but the aero config isn't ordered.  So that's not currently possible.  You might be able to come up with something using the macro system, but overall I believe this contradicts the "obvious" principle of aero so doesn't fit into aero's remit.

**Comment by licht1stein** [comment]
Thanks, I'll figure it out from here, now that I understand the context
