### ISSUE TITLE
#keyword doesn't return nil when #env var is missing

### ISSUE THREAD

**Issue by fuadsaud** [juxt/aero#110]
Hi!

I don't really understand if this is a bug or a misuse of tagged literals on my part. I want to specify a `:logger/min-level` key which could contain either a keyword or a complex data structure. I want to source the value either from an environment variable `LOGGER_MIN_LEVEL`, in which case I would like the string to be coerced into a keyword, or from a `#profile` dispatch. Here's what I tried:

```clojure
 :logger/min-level #or [#keyword #env LOGGER_MIN_LEVEL
                        #profile {:default :info

                                  :development
                                  [[#{"some-ns.*"} :trace]
                                   [#{"*"} :info]]

                                  :test
                                  [[#{"some-ns.*"} :trace]
                                   [#{"*"} :info]]}]
```

In the scenario where the env variable is not set, this returns an empty keyword `:`. Removing the `#keyword` tag from the above example makes it work (without the proper coercion, of course). If I understand correctly, `#keyword` is trying to coerce the vector, which generates the empty keyword. Is this the correct way to approach the problem?

**Comment by SevereOverfl0w** [comment]
I don't think `#or` is relevant here particularly.  `#keyword` always converts anything it gets to a keyword: https://github.com/juxt/aero/blob/814b0006a1699e8149045e55c4e112e61b983fe9/src/aero/core.cljc#L73-L77 so isn't suitable for doing something like `some->`

**Comment by fuadsaud** [comment]
Is this perhaps a misunderstanding on my end about application precedence or tagged literals? My intuition led me to interpret the above as:

```clojure
(#or (#keyword (#env LOGGER_MIN_LEVEL))
     (#profile ...))
```

But it seems that #keyword applies to both branches of the #or.

**Comment by SevereOverfl0w** [comment]
```clojure
(#or (#keyword (#env LOGGER_MIN_LEVEL))
     (#profile ...))
```

is correct!

But the problem is that `(#keyword (#env LOGGER_MIN_LEVEL))` becomes `(keyword (str nil))` which is `(keyword "")` which produces `:` and that causes your problem!

You could solve this by introducing a new method which behaves a little more like you expect:

```clojure
 (defmethod aero/reader 'ns/kw 
   [opts tag value] 
   (if (keyword? value) 
     value
     (some-> value keyword))) 
```

Usage of:

```
#or [#ns/kw #env LOGGER_MIN_LEVEL #profile {...}]`
```

should work then.

**Comment by fuadsaud** [comment]
@SevereOverfl0w ah, that makes perfect of sense, thanks for taking the time to elaborate.
