### ISSUE TITLE
Suggestion: #merge tag

### ISSUE THREAD

**Issue by weavejester** [juxt/aero#18]
Sometimes it might be useful to include a configuration, but slightly alter it.

For example, you might start with a config like:

``` edn
{:ring-defaults #include "site-defaults.edn"}
```

Then decide to alter a small part. Perhaps a `#merge` tag can merge configurations, in the same way that Leiningen merges profiles:

``` edn
{:ring-defaults
 #merge [#include "site-defaults.edn" {:static {:resources "foo/public"}}]}
```

I've written a [meta-merge](https://github.com/weavejester/meta-merge) library that might be useful. Feel free to close this issue if you think this is too heavy or not useful for Aero's specific goals.

**Comment by weavejester** [comment]
As an update, I've tried this out a little, and I found that it made configurations too complex in practice, so I no longer think this is necessarily a good idea.

**Comment by malcolmsparks** [comment]
Thanks @weavejester  - I can see the value of meta-merge in certain circumstances. But your point about real-world testing is useful too. I'll close the issue but we'll have a record of it, and feel free to open if you think there's value in adding a new tag literal to Aero's core.

**Comment by vincentjames501** [comment]
Playing around with aero, I could actually see value in this as I'm running into a similar situation now. I want to have a dev profile with optional overrides specified in a config file in dev-recources. Currently have something like:

``` clojure
#profile {:dev  {:config-overrides #include "config_overrides.edn"
                 :mobile           {:base-url     ^:ref [:config-overrides :mobile :base-url]
                                    :access-token ^:ref [:config-overrides :mobile :access-token]
                                    :extension-id #or [^:ref [:config-overrides :mobile :extension-id] #uuid "551de6ae-3d36-11e6-834a-3d1fcb19aadd"]
                                    :icop-id      ^:ref [:config-overrides :mobile :icop-id]}}
          :prod "omitted"}

```
