### ISSUE TITLE
#ref breaks #or

### ISSUE THREAD

**Issue by vise890** [juxt/aero#40]
Given the following config:
```clojure
{:env #or [#env FOO :foo]
 :foo #ref [:env]}
```
I'd expect `read-config` to return (assuming the env var `FOO` isn't set):
```clojure
{:env :foo, :foo :foo}
```
I get this instead:
```clojure
{:env nil, :foo nil}
```

**Comment by SevereOverfl0w** [comment]
Good catch, the new dependency resolver doesn't take into consideration that the `:value` may have unrelated (non-ref) tags in them.

I've updated the code to handle this case. There is a PR open to resolve this now. Thanks!

**Comment by vise890** [comment]
awesome, ty!
