### ISSUE TITLE
make a release including the 'require "fs"' commit?

### ISSUE THREAD

**Issue by sundbp** [juxt/aero#58]
I'm using aero for a node CLI app and everything works fine if the commit requiring fs is included (bit not the released 1.1.2). I was wondering if you would be willing to make a release of 1.1.3 including this change?

Thanks!

**Comment by sundbp** [comment]
Actually, there were more issues with nodejs requires and advanced compilation. I made a PR (https://github.com/juxt/aero/pull/59) that would make sense to include to make a release working more generally with nodejs.

**Comment by SevereOverfl0w** [comment]
1.1.3 includes these changes.
