### ISSUE TITLE
Friendly error message on missing include

### ISSUE THREAD

**Issue by andnils** [juxt/aero#65]
If I `#include` a non-existing file I get the following stack trace:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
	at clojure.java.io$fn__10992.invokeStatic(io.clj:288)
	at clojure.java.io$fn__10992.invoke(io.clj:288)
```
My use-case is a project template with database credentials stored in a private file that needs to be created by the user.
What I would like is a friendly message saying something like "File `secrets.edn` does not exist - please make a copy of `secrets.edn.template` and enter your password"...or something similar.

**Comment by andnils** [comment]
...or maybe I should write my own custom resolver for that!?

**Comment by SevereOverfl0w** [comment]
This exact message would need a custom resolver.

This message should only happen if you've set your resolver to `resource-resolver`, the default behavior is to inline `{:aero/missing-include "secrets.edn"}` where the include was missing.
