### ISSUE TITLE
Faulty set lookups in #user and #hostname

### ISSUE THREAD

**Issue by mhuebert** [juxt/aero#75]
First off, thanks for this library, I've found it very useful!

The set lookups in `#user` and `#hostname` readers use an `or` backoff instead of checking for key presence, and so will return the `:default` value when the desired key is present but has a falsy value.

https://github.com/juxt/aero/blob/master/src/aero/core.cljc#L92

One alternate approach is to expand set keys into individual entries, and then use `get` with default, eg:

```clj
(defn- expand-set-keys [m]
  (reduce-kv (fn [m k v]
               (if (set? k)
                 (reduce #(assoc %1 %2 v) m k)
                 (assoc m k v))) {} m))

(defmethod aero/reader 'hostname
  [{:keys [hostname]} tag value]
  (let [value (expand-set-keys value)]
    (get value hostname
         (get value :default))))
```

**Comment by SevereOverfl0w** [comment]
I think this approach makes sense.
