### ISSUE TITLE
`aero.core/deferred` does not transparently compose with subsequent data readers

### ISSUE THREAD

**Issue by ataggart** [juxt/aero#78]
#### Version
`[aero "1.1.3"]`

#### Problem

Custom data readers that use `aero.core/deferred` do not transparently compose with subsequent data readers.

#### Example

```
user=> (require '[aero.core :as aero])
nil

user=> (import java.io.StringReader)
java.io.StringReader

user=> (defmethod aero/reader 'custom [_ _ v]
  #_=>   (aero/deferred v))
#multifn[reader 0x74a1ace3]

user=> (defn read-str [s]
  #_=>   (aero/read-config (StringReader. s)))
#'user/read-str

user=> (read-str "{:x #boolean \"true\",
  #_=>             :y #boolean #custom \"true\"}")
{:x true, :y false}

user=> (read-str "{:x #long #custom \"123\"}")
Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:68).
For input string: "aero.core.Deferred@e53bb4c1"
```

Aside: Catching this was made harder because I was using `#boolean`, which silently yields `false` when given values outside of `#{"true" "false"}`. This kind of laxity could be dangerous.

#### Work-around

Given that the use case for `deferred` is mainly to compose with `#profile`:

1. Remove the use of `aero.core/deferred` from the custom reader.
2. Structure the config such that `#profile` will be resolved prior to the custom tag, e.g.:
   `{:x #long #custom #profile {:dev "foo" :prod "bar"}}`

**Comment by SevereOverfl0w** [comment]
My currently open pull request deprecated deferred altogether and made profile lazy. To resolve this exact issue.

**Comment by SevereOverfl0w** [comment]
For uses of wrapping around `#profile` (or any other conditionals), this use-case is now satisfied without any use of deferred in 1.1.4.

You can simply remove your use of it and your code will continue to work.

The reason it's not been replaced with `identity` is that some people worked around this issue by writing other tagged literals which would undefer, so that would be a breaking change.
