### ISSUE TITLE
Tags do not resolve in an obvious order.

### ISSUE THREAD

**Issue by mchughs** [juxt/aero#81]
The two following code blocks will have different values associated with the key `:result`.
```clojure
{:foo {:bar "my-value"}
:result #ref [:foo #keyword "bar"]}
```
will resolve to the map
```clojure
{:foo {:bar "my-value"}
:result nil}
```
where as
```clojure
{:foo {:bar "my-value"}
:my-key #keyword "bar"
:result #ref [:foo #ref [:my-key]]}
```
will resolve to the map
```clojure
{:foo {:bar "my-value"}
:my-key :bar
:result "my-value"}
```

My expectation would be that the output maps should be the exact same. (other than for the `:my-key :bar` key-value pair) I ideally shouldn't have to create an intermediary key to work-around reader composition rules.

**Comment by SevereOverfl0w** [comment]
Just to check, what version are you using? I wouldn't expect to see this in the latest version.

**Comment by SevereOverfl0w** [comment]
Just tested with 1.1.4, and this is working.

**Comment by mchughs** [comment]
Ah I was using 1.1.3 my mistake.

**Comment by SevereOverfl0w** [comment]
No problem. This was one of the things resolved in that, and it was only recently resolved.
