### ISSUE TITLE
v1.1.4 regression on parsing #ref inside of #or

### ISSUE THREAD

**Issue by shooit** [juxt/aero#84]
On v1.1.4 a config file containing:
```clojure
{:a "a"
 :b #or [#ref [:a] "I don't know what :a is"]
 :c #or [#ref [:d] "I don't know what :d is"]
 :d "d"
 :e #or [#ref [:z] "I don't know what :z is"]}
```
yields when parsed using `aero/read-config`
```clojure
{:a "a", :b "a", :c nil, :d "d", :e nil}
```
Regressions:
- `:c` is not parsed correctly despite `:d` being in the map (although after `:c`)
- the default value in the `#or` literal for `:e` is not returned 

On v1.1.3 the same config file yields
```clojure
{:a "a", :b "a", :c "d", :d "d", :e "I don't know what :z is"}
```
I view this as the expected result.

**Comment by SevereOverfl0w** [comment]
See #83 and #82.
