### ISSUE TITLE
Do magic without being forced to load files

### ISSUE THREAD

**Issue by jerger** [juxt/aero#89]
Is there a way to get the same cool functions as provided in 

`(read-config "config.edn")`

by soley act on software defined map? Sth. like 

`(resolve-config {:hello "World"})` ?

Not being forced to handle files (either on filesystem-by-path, by-resource or by-resource-in-jar) would make testing a lot easier ...

**Comment by SevereOverfl0w** [comment]
The config can be a reader, see the tests for aero.

**Comment by jerger** [comment]
you mean:

```
         (read-config
           (string-reader
             (binding [*print-meta* true]
               (pr-str {:user ^:ref [:karl]
                        :gardner {:favorite-color ^:ref [:color]}
                        :karl ^:ref [:gardner]
                        :color :blue})))))))
```

cool :-)
