### ISSUE TITLE
What is the recommended way to override (e.g., from a CLI) config values that are used by #ref?

### ISSUE THREAD

**Issue by bombaywalla** [juxt/aero#99]
Let's say I have a config.edn such as
```clojure
{:port #or [#env PORT 3000]
 :server {:port #ref [:port]}
 :client {:port #ref [:port]}
}
```
When I run the app, I give it the port on the command line like `app --port 5000`.
Inside the app, I have the CLI options as a map `{:port 5000}`.
I could do something like:
```clojure
(def opts {:port 5000})
(def raw-config (aero/read-config "config.edn"))
(def config (-> raw-config 
                (merge opts)
                (update-in [:server] merge opts)
                (update-in [:client] merge opts)))
```
Is there a better way?

**Comment by malcolmsparks** [comment]
Yes, create your own tag literal that allows your config to access command line parameters (perhaps stored as a map). The design of Aero is intended to encourage explicit over implicit configuration. In other words, if it is possible to override the port with a command line parameter, make that explicit so that someone reading the configuration can understand that the port number could be changed via the command line.

**Comment by bombaywalla** [comment]
Thank you.  That was very helpful.  I had not realized that the options passed to `aero/read-config` are also passed onto the tag literal reader.  For those that may come across this later, what I did was:
```clojure
;; config-test.edn
{:port #long #or [#cli [:cli :port] #env PORT #profile {:default 3000 :dev 5000}]
 :server {:port #ref [:port]}
 :client {:port #ref [:port]}
}
```

And at the call site...

```clojure
(require '[aero.core :as aero])
(defmethod aero/reader 'cli
  [opts _tag value]
  (get-in opts value))

(aero/read-config (io/resource "config-test.edn") (merge {} {}))
;; => {:port 3000, :server {:port 3000}, :client {:port 3000}}
(aero/read-config (io/resource "config-test.edn") (merge {:profile :dev} {}))
;; => {:port 5000, :server {:port 5000}, :client {:port 5000}}
(aero/read-config (io/resource "config-test.edn") (merge {:profile :dev} {:cli {:port 5500 :other 123}}))
;; => {:port 5500, :server {:port 5500}, :client {:port 5500}}
```

MUCH cleaner.

**Comment by bombaywalla** [comment]
Happy to create a PR to the README to add this example, if you'd like.
